title:              Jiseong's Blog
email:              wltjd5827@naver.com
description:        A Blog Theme by Start Bootstrap
author:             Jiseong Kim
#baseurl:            
url:                "https://Paykey.github.io"

# Social Profiles
twitter_username:  
github_username:    Paykey
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
